general:
  root_path: ../../vnncomp2025_benchmarks/benchmarks/cifar100_2024
  csv_name: instances.csv
model:
  onnx_optimization_flags: ["merge_bn"]
data:
  select_instance: [66]
solver:
  auto_enlarge_batch_size: True
  batch_size: 256
  beta-crown:
    lr_alpha: 0.1
    lr_beta: 0.2
    iteration: 10
  alpha-crown:
    lr_alpha: 0.25
    iteration: 20
    full_conv_alpha: False
bab:
  interm_transfer: False
  override_timeout: 300
  branching:
    method: kfsb
    candidates: 7
    reduceop: max